-
  name: 1card
  caption:
    text:
      - default:
        - en-US: 'Learn words for the TOEFL with cards'
        - ru-RU: 'Учите слова к TOEFL с помощью карточек'
    size:
      - 5.5:
        - default: 75
      - default:
        - default: 0
    font:
      - default:
        - default: HelveticaNeue-Medium.ttf
    color:
      - default:
        - default: 'white'
    offsets:
      - 12.9:
        - default:
            left: 200
            right: 200
            top: 120
            bottom: 60
      - default:
        - default:
            left: 65
            right: 65
            top: 60
            bottom: 20
  background:
    - 12.9:
      - default: bg_ipad.png
    - default:
      - default: bg.png
-
  name: 2hard
  caption:
    text:
      - default:
        - en-US: 'Swipe the card to the left if the problem is too hard for you'
        - ru-RU: 'Смахните влево, если слишком сложно'
    size:
      - 5.5:
        - default: 75
      - default:
        - default: 0
    font:
      - default:
        - default: HelveticaNeue-Medium.ttf
    color:
      - default:
        - default: 'white'
    offsets:
      - 12.9:
        - default:
            left: 200
            right: 200
            top: 120
            bottom: 60
      - default:
        - default:
            left: 65
            right: 65
            top: 60
            bottom: 20
  background:
    - 12.9:
      - default: bg_ipad.png
    - default:
      - default: bg.png
-
  name: 3simple
  caption:
    text:
      - default:
        - en-US: 'Swipe the card to the right if the problem is too easy for you'
        - ru-RU: 'Смахните вправо, если слишком просто'
    size:
      - 5.5:
        - default: 75
      - default:
        - default: 0
    font:
      - default:
        - default: HelveticaNeue-Medium.ttf
    color:
      - default:
        - default: 'white'
    offsets:
      - 12.9:
        - default:
            left: 200
            right: 200
            top: 120
            bottom: 60
      - default:
        - default:
            left: 65
            right: 65
            top: 60
            bottom: 20
  background:
    - 12.9:
      - default: bg_ipad.png
    - default:
      - default: bg.png
-
  name: 4stats
  caption:
    text:
      - default:
        - en-US: 'Track your learning progress'
        - ru-RU: 'Следите за своим прогрессом'
    size:
      - 5.5:
        - default: 75
      - default:
        - default: 0
    font:
      - default:
        - default: HelveticaNeue-Medium.ttf
    color:
      - default:
        - default: 'white'
    offsets:
      - 12.9:
        - default:
            left: 200
            right: 200
            top: 120
            bottom: 60
      - default:
        - default:
            left: 65
            right: 65
            top: 60
            bottom: 20
  background:
    - 12.9:
      - default: bg_ipad.png
    - default:
      - default: bg.png
